export const sampleObjectArray = [
  {
    id: "roofus-1",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
  {
    id: "roofus-2",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
  {
    id:"roofus-3",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
  {
    id:"roofus-4",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
  {
    id:"roofus-5",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
  {
    id:"roofus-6",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
  {
    id:"roofus-7",
    name: "Roofus",
    location: "Foster Care",
    breed: "Corgi",
    age: 6,
    sex: "Male",
    size: "Small",
    type: "Cat",
    description: "ROOFUS IS BEST DOG",
    img: "https://random.dog/00186969-c51d-462b-948b-30a7e1735908.jpg",
  },
];

export const adoptionStories = [
  {
    title: "Spooky",
    description: "Spooky was a timid, quiet cat when she came to our shelter, but she has now blossomed into a loving and social kitty with the help of her new owners.",
    img: "../assets/stories/spooky.png",
  },
  {
    title: "Nugget",
    description: "This little munchkin has been thriving in her new home with her two siblings, Fry and Onion.",
    img: "../assets/stories/nugget.png",
  },
  {
    title: "Umbreon and Espeon",
    description: "Together since birth, Umbreon and Espeon were able to be adopted together and have been living a peaceful life with their owner Ash.",
    img: "../assets/stories/umbreonespeon.jpeg",
  },
  {
    title: "Crouton",
    description: "This sweet kitty, affectionately named after her love for croutons, has made a best friend for life.",
    img: "../assets/stories/crouton.jpg",
  },
  {
    title: "Goomba",
    description: "Despite his stubby legs, Goomba loves to go on lots of adventures with his new owner.",
    img: "../assets/stories/goomba.png",
  },
  {
    title: "Duck",
    description: "This energetic pup now has a huge backyard to run around in, where he likes to chase squirrels and play fetch.",
    img: "../assets/stories/duck.png",
  },
  {
    title: "Luigi",
    description: "Luigi's sweet personality and piercing eyes captured the hearts of his owners, Dwight and Angela.",
    img: "../assets/stories/luigi.png",
  },
  {
    title: "Hank",
    description: "Hank may be an old man, but he's loving his comfortable life in a new home and loves to lay on the couch watching the world go by.",
    img: "../assets/stories/hank.jpg",
  },
  {
    title: "Toast",
    description: "This little guy came right out of his shell after being adopted, and he now likes to knock plant pots off of his owner's windowsill.",
    img: "../assets/stories/toast.jpg",
  },
];